 -- NDefines.NAI.DIPLOMACY_SEND_EXPEDITIONARY_BASE = 20
NDefines.NAI.DIPLOMACY_FACTION_WRONG_IDEOLOGY_PENALTY = 40
NDefines.NAI.DIPLOMACY_FACTION_SAME_IDEOLOGY_MAJOR = 10
NDefines.NAI.DIPLOMACY_FACTION_NEUTRALITY_PENALTY = 25
 -- NDefines.NMilitary.PLANNING_DECAY = 0.01
 -- NDefines.NMilitary.PLANNING_GAIN = 0.02
 -- NDefines.NMilitary.PLANNING_MAX = 0.5    